accounts:
- id: gh_89196407
  last_update: '2026-02-10T20:18:40.945263'
  name: 人民日报
- id: gh_20235163
  last_update: '2026-02-10T20:18:42.950925'
  name: 新华社
- id: gh_7904505
  last_update: '2026-02-10T20:18:44.959972'
  name: 央视新闻
